### ISSUE TITLE
hi I was trying to request a channel for 1,000,000 sats and I accidentally input that amount in "lncli sendpayment --keysend  --amt 1000000 \ --dest 02ab583d430015f3b6b41730434b5fac264901b50199f0b9becc0a98a365f581a9 \ --data 1667785070=01,34349339=03235039ca3fae1808e253940b0b09abdb2b532bb0c20faa94221cdb4ab5de8afb". my public key is in the command line. will my bitcoin be refunded?

### ISSUE THREAD

**Issue by Iamillenial** [lnd-routing/lnd-routing#5]

**Comment by lnd-routing** [comment]
We have manually refunded the amount minus routing fees. 

Payments with invalid parameters have to be refunded manually rather than automatically, since we cannot predict which part would be invalid. 

We highly suggest using the python script if you're at all uncomfortable with the CLI.

Thank you for using our service.

**Comment by Iamillenial** [comment]
Much appreciated
